package com.minimapcleanser;

import lombok.extern.slf4j.Slf4j;
import net.runelite.api.Client;
import net.runelite.api.gameval.DBTableID;
import net.runelite.api.gameval.ObjectID;
import net.runelite.api.gameval.VarPlayerID;
import net.runelite.api.gameval.VarbitID;

@Slf4j
enum quests
{
    ANIMALMAGNETISM(ObjectID.QUEST_START_ICON_ANIMALMAGNETISM, DBTableID.Quest.Row.QUEST_ANIMALMAGNETISM, VarbitID.ANMA_MAIN, null),
    ANOTHERSLICEOFHAM(ObjectID.QUEST_START_ICON_ANOTHERSLICEOFHAM, DBTableID.Quest.Row.QUEST_ANOTHERSLICEOFHAM, VarbitID.SLICE_QUEST, null),
    ASCENTOFARCEUUS(ObjectID.QUEST_START_ICON_ASCENTOFARCEUUS, DBTableID.Quest.Row.QUEST_ASCENTOFARCEUUS, VarbitID.ARCQUEST, null),
    ATFIRSTLIGHT(ObjectID.QUEST_START_ICON_ATFIRSTLIGHT, DBTableID.Quest.Row.QUEST_ATFIRSTLIGHT, VarbitID.AFL, null),
    BELOWICEMOUNTAIN(ObjectID.QUEST_START_ICON_BELOWICEMOUNTAIN, DBTableID.Quest.Row.QUEST_BELOWICEMOUNTAIN, VarbitID.BIM, null),
    BENEATHCURSEDSANDS(ObjectID.QUEST_START_ICON_BENEATHCURSEDSANDS, DBTableID.Quest.Row.QUEST_BENEATHCURSEDSANDS, VarbitID.BCS, null),
    BETWEENAROCK(ObjectID.QUEST_START_ICON_BETWEENAROCK, DBTableID.Quest.Row.QUEST_BETWEENAROCK, VarbitID.DWARFROCK_QUEST, null),
    BIGCHOMPYBIRDHUNTING(ObjectID.QUEST_START_ICON_BIGCHOMPYBIRDHUNTING, DBTableID.Quest.Row.QUEST_BIGCHOMPYBIRDHUNTING, null, VarPlayerID.CHOMPYBIRD),
    BIOHAZARD(ObjectID.QUEST_START_ICON_BIOHAZARD, DBTableID.Quest.Row.QUEST_BIOHAZARD, null, VarPlayerID.BIOHAZARD),
    BLACKKNIGHTSFORTRESS(ObjectID.QUEST_START_ICON_BLACKKNIGHTSFORTRESS, DBTableID.Quest.Row.QUEST_BLACKKNIGHTSFORTRESS, null, VarPlayerID.SPY),
    BONEVOYAGE(ObjectID.QUEST_START_ICON_BONEVOYAGE, DBTableID.Quest.Row.QUEST_BONEVOYAGE, VarbitID.FOSSILQUEST_PROGRESS, null),
    CABINFEVER(ObjectID.QUEST_START_ICON_CABINFEVER, DBTableID.Quest.Row.QUEST_CABINFEVER, null, VarPlayerID.FEVER_QUEST),
    CHILDRENOFTHESUN(ObjectID.QUEST_START_ICON_CHILDRENOFTHESUN, DBTableID.Quest.Row.QUEST_CHILDRENOFTHESUN, VarbitID.VMQ1, null),
    CLIENTOFKOUREND(ObjectID.QUEST_START_ICON_CLIENTOFKOUREND, DBTableID.Quest.Row.QUEST_CLIENTOFKOUREND, VarbitID.VEOS_PROGRESS, null),
    CLOCKTOWER(ObjectID.QUEST_START_ICON_CLOCKTOWER, DBTableID.Quest.Row.QUEST_CLOCKTOWER, null, VarPlayerID.COGQUEST),
    COLDWAR(ObjectID.QUEST_START_ICON_COLDWAR, DBTableID.Quest.Row.QUEST_COLDWAR, VarbitID.PENG_QUEST, null),
    CONTACT(ObjectID.QUEST_START_ICON_CONTACT, DBTableID.Quest.Row.QUEST_CONTACT, VarbitID.CONTACT, null),
    COOKSASSISTANT(ObjectID.QUEST_START_ICON_COOKSASSISTANT, DBTableID.Quest.Row.QUEST_COOKSASSISTANT, null, VarPlayerID.COOKQUEST),
    CORSAIRCURSE(ObjectID.QUEST_START_ICON_CORSAIRCURSE, DBTableID.Quest.Row.QUEST_CORSAIRCURSE, VarbitID.CORSCURS_PROGRESS, null),
    CREATUREOFFENKENSTRAIN(ObjectID.QUEST_START_ICON_CREATUREOFFENKENSTRAIN, DBTableID.Quest.Row.QUEST_CREATUREOFFENKENSTRAIN, null, VarPlayerID.FENK_QUEST),
    CURSEOFARRAV(ObjectID.QUEST_START_ICON_CURSEOFARRAV, DBTableID.Quest.Row.QUEST_CURSEOFARRAV, VarbitID.COA, null),
    DARKNESSOFHALLOWVALE(ObjectID.QUEST_START_ICON_DARKNESSOFHALLOWVALE, DBTableID.Quest.Row.QUEST_DARKNESSOFHALLOWVALE, VarbitID.MYQ3_MAIN_QUEST, null),
    DEATHONTHEISLE(ObjectID.QUEST_START_ICON_DEATHONTHEISLE, DBTableID.Quest.Row.QUEST_DEATHONTHEISLE, VarbitID.DOTI, null),
    DEATHPLATEAU(ObjectID.QUEST_START_ICON_DEATHPLATEAU, DBTableID.Quest.Row.QUEST_DEATHPLATEAU, null, VarPlayerID.DEATH_EQUIPROOM),
    DEATHTOTHEDORGESHUUN(ObjectID.QUEST_START_ICON_DEATHTOTHEDORGESHUUN, DBTableID.Quest.Row.QUEST_DEATHTOTHEDORGESHUUN, VarbitID.DTTD_MAIN, null),
    DEFENDEROFVARROCK(ObjectID.QUEST_START_ICON_DEFENDEROFVARROCK, DBTableID.Quest.Row.QUEST_DEFENDEROFVARROCK, VarbitID.DOV, null),
    DEMONSLAYER(ObjectID.QUEST_START_ICON_DEMONSLAYER, DBTableID.Quest.Row.QUEST_DEMONSLAYER, VarbitID.DEMONSLAYER_MAIN, null),
    DEPTHSOFDESPAIR(ObjectID.QUEST_START_ICON_DEPTHSOFDESPAIR, DBTableID.Quest.Row.QUEST_DEPTHSOFDESPAIR, VarbitID.HOSIDIUSQUEST, null),
    DESERTTREASURE(ObjectID.QUEST_START_ICON_DESERTTREASURE, DBTableID.Quest.Row.QUEST_DESERTTREASURE, VarbitID.DESERTTREASURE, null),
    DESERTTREASURE2(ObjectID.QUEST_START_ICON_DESERTTREASURE2, DBTableID.Quest.Row.QUEST_DESERTTREASURE2, VarbitID.DT2, null),
    DEVIOUSMINDS(ObjectID.QUEST_START_ICON_DEVIOUSMINDS, DBTableID.Quest.Row.QUEST_DEVIOUSMINDS, VarbitID.DEVIOUS_MAIN, null),
    DIGSITE(ObjectID.QUEST_START_ICON_DIGSITE, DBTableID.Quest.Row.QUEST_DIGSITE, null, VarPlayerID.ITEXAMLEVEL),
    DORICS(ObjectID.QUEST_START_ICON_DORICS, DBTableID.Quest.Row.QUEST_DORICS, null, VarPlayerID.DORICQUEST),
    DRAGONSLAYER1(ObjectID.QUEST_START_ICON_DRAGONSLAYER1, DBTableID.Quest.Row.QUEST_DRAGONSLAYER1, null, VarPlayerID.DRAGONQUEST),
    DRAGONSLAYER2(ObjectID.QUEST_START_ICON_DRAGONSLAYER2, DBTableID.Quest.Row.QUEST_DRAGONSLAYER2, VarbitID.DS2, null),
    DREAMMENTOR(ObjectID.QUEST_START_ICON_DREAMMENTOR, DBTableID.Quest.Row.QUEST_DREAMMENTOR, VarbitID.DREAM_PROG, null),
    DRUIDICRITUAL(ObjectID.QUEST_START_ICON_DRUIDICRITUAL, DBTableID.Quest.Row.QUEST_DRUIDICRITUAL, null, VarPlayerID.DRUIDQUEST),
    DWARFCANNON(ObjectID.QUEST_START_ICON_DWARFCANNON, DBTableID.Quest.Row.QUEST_DWARFCANNON, null, VarPlayerID.MCANNON),
    EADGARSRUSE(ObjectID.QUEST_START_ICON_EADGARSRUSE, DBTableID.Quest.Row.QUEST_EADGARSRUSE, null, VarPlayerID.EADGAR_QUEST),
    EAGLESPEAK(ObjectID.QUEST_START_ICON_EAGLESPEAK, DBTableID.Quest.Row.QUEST_EAGLESPEAK, VarbitID.EAGLEPEAK_QUEST, null),
    ELEMENTALWORKSHOP1(ObjectID.QUEST_START_ICON_ELEMENTALWORKSHOP1, DBTableID.Quest.Row.QUEST_ELEMENTALWORKSHOP1, null, VarPlayerID.ELEMENTAL_WORKSHOP_BITS),
    ELEMENTALWORKSHOP2(ObjectID.QUEST_START_ICON_ELEMENTALWORKSHOP2, DBTableID.Quest.Row.QUEST_ELEMENTALWORKSHOP2, VarbitID.ELEMENTAL_QUEST_2_MAIN, null),
    ENAKHRASLAMENT(ObjectID.QUEST_START_ICON_ENAKHRASLAMENT, DBTableID.Quest.Row.QUEST_ENAKHRASLAMENT, VarbitID.ENAKH_QUEST, null),
    ENLIGHTENEDJOURNEY(ObjectID.QUEST_START_ICON_ENLIGHTENEDJOURNEY, DBTableID.Quest.Row.QUEST_ENLIGHTENEDJOURNEY, VarbitID.ZEP_QUEST, null),
    ERNESTTHECHICKEN(ObjectID.QUEST_START_ICON_ERNESTTHECHICKEN, DBTableID.Quest.Row.QUEST_ERNESTTHECHICKEN, null, VarPlayerID.HAUNTED),
    ETHICALLYACQUIREDANTIQUITIES(ObjectID.QUEST_START_ICON_ETHICALLYACQUIREDANTIQUITIES, DBTableID.Quest.Row.QUEST_ETHICALLYACQUIREDANTIQUITIES, VarbitID.EAA, null),
    EYESOFGLOUPHRIE(ObjectID.QUEST_START_ICON_EYESOFGLOUPHRIE, DBTableID.Quest.Row.QUEST_EYESOFGLOUPHRIE, VarbitID.EYEGLO_QUEST, null),
    FAIRYTALE1(ObjectID.QUEST_START_ICON_FAIRYTALE1, DBTableID.Quest.Row.QUEST_FAIRYTALE1, VarbitID.FAIRY_FARMERS_QUEST, null),
    FAIRYTALE2(ObjectID.QUEST_START_ICON_FAIRYTALE2, DBTableID.Quest.Row.QUEST_FAIRYTALE2, VarbitID.FAIRY2_QUEENCURE_QUEST, null),
    FAMILYCREST(ObjectID.QUEST_START_ICON_FAMILYCREST, DBTableID.Quest.Row.QUEST_FAMILYCREST, null, VarPlayerID.CRESTQUEST),
    FEUD(ObjectID.QUEST_START_ICON_FEUD, DBTableID.Quest.Row.QUEST_FEUD, VarbitID.FEUD_VAR, null),
    FIGHTARENA(ObjectID.QUEST_START_ICON_FIGHTARENA, DBTableID.Quest.Row.QUEST_FIGHTARENA, null, VarPlayerID.ARENAQUEST),
    FINALDAWN(ObjectID.QUEST_START_ICON_FINALDAWN, DBTableID.Quest.Row.QUEST_FINALDAWN, VarbitID.VMQ4, null),
    FISHINGCONTEST(ObjectID.QUEST_START_ICON_FISHINGCONTEST, DBTableID.Quest.Row.QUEST_FISHINGCONTEST, null, VarPlayerID.FISHINGCOMPO),
    FORGETTABLETALE(ObjectID.QUEST_START_ICON_FORGETTABLETALE, DBTableID.Quest.Row.QUEST_FORGETTABLETALE, VarbitID.FORGET_QUEST, null),
    FORSAKENTOWER(ObjectID.QUEST_START_ICON_FORSAKENTOWER, DBTableID.Quest.Row.QUEST_FORSAKENTOWER, VarbitID.LOVAQUEST, null),
    FREMENNIKEXILES(ObjectID.QUEST_START_ICON_FREMENNIKEXILES, DBTableID.Quest.Row.QUEST_FREMENNIKEXILES, VarbitID.VIKINGEXILE, null),
    FREMENNIKISLES(ObjectID.QUEST_START_ICON_FREMENNIKISLES, DBTableID.Quest.Row.QUEST_FREMENNIKISLES, VarbitID.FRIS_QUEST, null),
    FREMENNIKTRIALS(ObjectID.QUEST_START_ICON_FREMENNIKTRIALS, DBTableID.Quest.Row.QUEST_FREMENNIKTRIALS, null, VarPlayerID.VIKING),
    GARDENOFDEATH(ObjectID.QUEST_START_ICON_GARDENOFDEATH, DBTableID.Quest.Row.QUEST_GARDENOFDEATH, VarbitID.TGOD, null),
    GARDENOFTRANQUILLITY(ObjectID.QUEST_START_ICON_GARDENOFTRANQUILLITY, DBTableID.Quest.Row.QUEST_GARDENOFTRANQUILLITY, VarbitID.GARDEN_QUEST, null),
    GERTRUDESCAT(ObjectID.QUEST_START_ICON_GERTRUDESCAT, DBTableID.Quest.Row.QUEST_GERTRUDESCAT, null, VarPlayerID.FLUFFS),
    GETTINGAHEAD(ObjectID.QUEST_START_ICON_GETTINGAHEAD, DBTableID.Quest.Row.QUEST_GETTINGAHEAD, VarbitID.GA, null),
    GHOSTSAHOY(ObjectID.QUEST_START_ICON_GHOSTSAHOY, DBTableID.Quest.Row.QUEST_GHOSTSAHOY, VarbitID.AHOY_QUESTVAR, null),
    GIANTDWARF(ObjectID.QUEST_START_ICON_GIANTDWARF, DBTableID.Quest.Row.QUEST_GIANTDWARF, VarbitID.GIANTDWARF_QUEST, null),
    GOBLINDIPLOMACY(ObjectID.QUEST_START_ICON_GOBLINDIPLOMACY, DBTableID.Quest.Row.QUEST_GOBLINDIPLOMACY, VarbitID.GOBDIP_MAIN, null),
    GOLEM(ObjectID.QUEST_START_ICON_GOLEM, DBTableID.Quest.Row.QUEST_GOLEM, VarbitID.GOLEM_A, null),
    GRANDTREE(ObjectID.QUEST_START_ICON_GRANDTREE, DBTableID.Quest.Row.QUEST_GRANDTREE, null, VarPlayerID.GRANDTREE),
    GREATBRAINROBBERY(ObjectID.QUEST_START_ICON_GREATBRAINROBBERY, DBTableID.Quest.Row.QUEST_GREATBRAINROBBERY, null, VarPlayerID.BRAIN_QUEST_VAR),
    GRIMTALES(ObjectID.QUEST_START_ICON_GRIMTALES, DBTableID.Quest.Row.QUEST_GRIMTALES, VarbitID.GRIM_QUEST, null),
    HANDINTHESAND(ObjectID.QUEST_START_ICON_HANDINTHESAND, DBTableID.Quest.Row.QUEST_HANDINTHESAND, VarbitID.HANDSAND_QUEST, null),
    HAUNTEDMINE(ObjectID.QUEST_START_ICON_HAUNTEDMINE, DBTableID.Quest.Row.QUEST_HAUNTEDMINE, null, VarPlayerID.HAUNTEDMINE),
    HAZEELCULT(ObjectID.QUEST_START_ICON_HAZEELCULT, DBTableID.Quest.Row.QUEST_HAZEELCULT, null, VarPlayerID.HAZEELCULTQUEST),
    HEARTOFDARKNESS(ObjectID.QUEST_START_ICON_HEARTOFDARKNESS, DBTableID.Quest.Row.QUEST_HEARTOFDARKNESS, VarbitID.VMQ3, null),
    HEROES(ObjectID.QUEST_START_ICON_HEROES, DBTableID.Quest.Row.QUEST_HEROES, null, VarPlayerID.HEROQUEST),
    HOLYGRAIL(ObjectID.QUEST_START_ICON_HOLYGRAIL, DBTableID.Quest.Row.QUEST_HOLYGRAIL, null, VarPlayerID.GRAIL),
    HORRORFROMTHEDEEP(ObjectID.QUEST_START_ICON_HORRORFROMTHEDEEP, DBTableID.Quest.Row.QUEST_HORRORFROMTHEDEEP, VarbitID.HORRORQUEST, null),
    ICTHLARINSLITTLEHELPER(ObjectID.QUEST_START_ICON_ICTHLARINSLITTLEHELPER, DBTableID.Quest.Row.QUEST_ICTHLARINSLITTLEHELPER, VarbitID.ICS_LITTLE_VAR, null),
    IMPCATCHER(ObjectID.QUEST_START_ICON_IMPCATCHER, DBTableID.Quest.Row.QUEST_IMPCATCHER, null, VarPlayerID.IMP),
    INAIDOFTHEMYREQUE(ObjectID.QUEST_START_ICON_INAIDOFTHEMYREQUE, DBTableID.Quest.Row.QUEST_INAIDOFTHEMYREQUE, VarbitID.MYREQUE_2_QUEST, null),
    INSEARCHOFTHEMYREQUE(ObjectID.QUEST_START_ICON_INSEARCHOFTHEMYREQUE, DBTableID.Quest.Row.QUEST_INSEARCHOFTHEMYREQUE, null, VarPlayerID.ROUTEQUEST),
    JUNGLEPOTION(ObjectID.QUEST_START_ICON_JUNGLEPOTION, DBTableID.Quest.Row.QUEST_JUNGLEPOTION, null, VarPlayerID.JUNGLEPOTION),
    KINGDOMDIVIDED(ObjectID.QUEST_START_ICON_KINGDOMDIVIDED, DBTableID.Quest.Row.QUEST_KINGDOMDIVIDED, VarbitID.AKD, null),
    KINGSRANSOM(ObjectID.QUEST_START_ICON_KINGSRANSOM, DBTableID.Quest.Row.QUEST_KINGSRANSOM, VarbitID.KR_QUEST, null),
    KNIGHTSSWORD(ObjectID.QUEST_START_ICON_KNIGHTSSWORD, DBTableID.Quest.Row.QUEST_KNIGHTSSWORD, null, VarPlayerID.SQUIRE),
    LANDOFTHEGOBLINS(ObjectID.QUEST_START_ICON_LANDOFTHEGOBLINS, DBTableID.Quest.Row.QUEST_LANDOFTHEGOBLINS, VarbitID.LOTG, null),
    LEGENDS(ObjectID.QUEST_START_ICON_LEGENDS, DBTableID.Quest.Row.QUEST_LEGENDS, null, VarPlayerID.LEGENDSQUEST),
    LOSTCITY(ObjectID.QUEST_START_ICON_LOSTCITY, DBTableID.Quest.Row.QUEST_LOSTCITY, null, VarPlayerID.ZANARIS),
    LOSTTRIBE(ObjectID.QUEST_START_ICON_LOSTTRIBE, DBTableID.Quest.Row.QUEST_LOSTTRIBE, VarbitID.LOST_TRIBE_QUEST, null),
    LUNARDIPLOMACY(ObjectID.QUEST_START_ICON_LUNARDIPLOMACY, DBTableID.Quest.Row.QUEST_LUNARDIPLOMACY, VarbitID.LUNAR_QUEST_MAIN, null),
    MAKINGFRIENDSWITHMYARM(ObjectID.QUEST_START_ICON_MAKINGFRIENDSWITHMYARM, DBTableID.Quest.Row.QUEST_MAKINGFRIENDSWITHMYARM, VarbitID.MY2ARM_STATUS, null),
    MAKINGHISTORY(ObjectID.QUEST_START_ICON_MAKINGHISTORY, DBTableID.Quest.Row.QUEST_MAKINGHISTORY, VarbitID.MAKINGHISTORY_PROG, null),
    MEATANDGREET(ObjectID.QUEST_START_ICON_MEATANDGREET, DBTableID.Quest.Row.QUEST_MEATANDGREET, VarbitID.MAG, null),
    MERLINSCRYSTAL(ObjectID.QUEST_START_ICON_MERLINSCRYSTAL, DBTableID.Quest.Row.QUEST_MERLINSCRYSTAL, null, VarPlayerID.ARTHUR),
    MISTHALINMYSTERY(ObjectID.QUEST_START_ICON_MISTHALINMYSTERY, DBTableID.Quest.Row.QUEST_MISTHALINMYSTERY, VarbitID.MISTMYST_PROGRESS, null),
    MONKEYMADNESS1(ObjectID.QUEST_START_ICON_MONKEYMADNESS1, DBTableID.Quest.Row.QUEST_MONKEYMADNESS1, null, VarPlayerID.MM_MAIN),
    MONKEYMADNESS2(ObjectID.QUEST_START_ICON_MONKEYMADNESS2, DBTableID.Quest.Row.QUEST_MONKEYMADNESS2, VarbitID.MM2_PROGRESS, null),
    MONKSFRIEND(ObjectID.QUEST_START_ICON_MONKSFRIEND, DBTableID.Quest.Row.QUEST_MONKSFRIEND, null, VarPlayerID.DRUNKMONKQUEST),
    MOUNTAINDAUGHTER(ObjectID.QUEST_START_ICON_MOUNTAINDAUGHTER, DBTableID.Quest.Row.QUEST_MOUNTAINDAUGHTER, VarbitID.MDAUGHTER_QUEST_VAR, null),
    MOURNINGSENDPART1(ObjectID.QUEST_START_ICON_MOURNINGSENDPART1, DBTableID.Quest.Row.QUEST_MOURNINGSENDPART1, null, VarPlayerID.MOURNING_QUEST),
    MOURNINGSENDPART2(ObjectID.QUEST_START_ICON_MOURNINGSENDPART2, DBTableID.Quest.Row.QUEST_MOURNINGSENDPART2, VarbitID.MOURNING_QUEST_MAIN, null),
    MURDERMYSTERY(ObjectID.QUEST_START_ICON_MURDERMYSTERY, DBTableID.Quest.Row.QUEST_MURDERMYSTERY, null, VarPlayerID.MURDERQUEST),
    MYARMSBIGADVENTURE(ObjectID.QUEST_START_ICON_MYARMSBIGADVENTURE, DBTableID.Quest.Row.QUEST_MYARMSBIGADVENTURE, VarbitID.MYARM, null),
    NATURESPIRIT(ObjectID.QUEST_START_ICON_NATURESPIRIT, DBTableID.Quest.Row.QUEST_NATURESPIRIT, null, VarPlayerID.DRUIDSPIRIT),
    NIGHTATTHETHEATRE(ObjectID.QUEST_START_ICON_NIGHTATTHETHEATRE, DBTableID.Quest.Row.QUEST_NIGHTATTHETHEATRE, VarbitID.TOBQUEST, null),
    OBSERVATORY(ObjectID.QUEST_START_ICON_OBSERVATORY, DBTableID.Quest.Row.QUEST_OBSERVATORY, null, VarPlayerID.ITGRONIGEN),
    OLAFS(ObjectID.QUEST_START_ICON_OLAFS, DBTableID.Quest.Row.QUEST_OLAFS, VarbitID.OLAF_QUEST_VAR, null),
    ONESMALLFAVOUR(ObjectID.QUEST_START_ICON_ONESMALLFAVOUR, DBTableID.Quest.Row.QUEST_ONESMALLFAVOUR, null, VarPlayerID.ONESMALLFAVOUR),
    PATHOFGLOUPHRIE(ObjectID.QUEST_START_ICON_PATHOFGLOUPHRIE, DBTableID.Quest.Row.QUEST_PATHOFGLOUPHRIE, VarbitID.POG, null),
    PERILOUSMOONS(ObjectID.QUEST_START_ICON_PERILOUSMOONS, DBTableID.Quest.Row.QUEST_PERILOUSMOONS, VarbitID.PMOON_QUEST, null),
    PIRATESTREASURE(ObjectID.QUEST_START_ICON_PIRATESTREASURE, DBTableID.Quest.Row.QUEST_PIRATESTREASURE, null, VarPlayerID.HUNT),
    PLAGUECITY(ObjectID.QUEST_START_ICON_PLAGUECITY, DBTableID.Quest.Row.QUEST_PLAGUECITY, null, VarPlayerID.ELENAQUEST),
    PORCINEOFINTEREST(ObjectID.QUEST_START_ICON_PORCINEOFINTEREST, DBTableID.Quest.Row.QUEST_PORCINEOFINTEREST, VarbitID.PORCINE, null),
    PRIESTINPERIL(ObjectID.QUEST_START_ICON_PRIESTINPERIL, DBTableID.Quest.Row.QUEST_PRIESTINPERIL, null, VarPlayerID.PRIESTPERIL),
    PRINCEALIRESCUE(ObjectID.QUEST_START_ICON_PRINCEALIRESCUE, DBTableID.Quest.Row.QUEST_PRINCEALIRESCUE, null, VarPlayerID.PRINCEQUEST),
    QUEENOFTHIEVES(ObjectID.QUEST_START_ICON_QUEENOFTHIEVES, DBTableID.Quest.Row.QUEST_QUEENOFTHIEVES, VarbitID.PISCQUEST, null),
    RAGANDBONEMAN1(ObjectID.QUEST_START_ICON_RAGANDBONEMAN1, DBTableID.Quest.Row.QUEST_RAGANDBONEMAN1, null, VarPlayerID.RAG_QUEST),
    RAGANDBONEMAN2(ObjectID.QUEST_START_ICON_RAGANDBONEMAN2, DBTableID.Quest.Row.QUEST_RAGANDBONEMAN2, null, VarPlayerID.RAG_QUEST),
    RATCATCHERS(ObjectID.QUEST_START_ICON_RATCATCHERS, DBTableID.Quest.Row.QUEST_RATCATCHERS, VarbitID.RATCATCH_VAR, null),
    RECIPEFORDISASTER(ObjectID.QUEST_START_ICON_RECIPEFORDISASTER, DBTableID.Quest.Row.QUEST_RECIPEFORDISASTER, VarbitID.HUNDRED_MAIN_QUEST_VAR, null),
    RECRUITMENTDRIVE(ObjectID.QUEST_START_ICON_RECRUITMENTDRIVE, DBTableID.Quest.Row.QUEST_RECRUITMENTDRIVE, VarbitID.RD_MAIN, null),
    REGICIDE(ObjectID.QUEST_START_ICON_REGICIDE, DBTableID.Quest.Row.QUEST_REGICIDE, null, VarPlayerID.REGICIDE_QUEST),
    RESTLESSGHOST(ObjectID.QUEST_START_ICON_RESTLESSGHOST, DBTableID.Quest.Row.QUEST_RESTLESSGHOST, null, VarPlayerID.PRIESTSTART),
    RIBBITINGTALE(ObjectID.QUEST_START_ICON_RIBBITINGTALE, DBTableID.Quest.Row.QUEST_RIBBITINGTALE, VarbitID.FROG_QUEST, null),
    ROMEOANDJULIET(ObjectID.QUEST_START_ICON_ROMEOANDJULIET, DBTableID.Quest.Row.QUEST_ROMEOANDJULIET, null, VarPlayerID.RJQUEST),
    ROVINGELVES(ObjectID.QUEST_START_ICON_ROVINGELVES, DBTableID.Quest.Row.QUEST_ROVINGELVES, null, VarPlayerID.ROVING_ELVES_QUEST),
    ROYALTROUBLE(ObjectID.QUEST_START_ICON_ROYALTROUBLE, DBTableID.Quest.Row.QUEST_ROYALTROUBLE, VarbitID.ROYAL_QUEST, null),
    RUMDEAL(ObjectID.QUEST_START_ICON_RUMDEAL, DBTableID.Quest.Row.QUEST_RUMDEAL, null, VarPlayerID.DEAL_QUEST),
    RUNEMYSTERIES(ObjectID.QUEST_START_ICON_RUNEMYSTERIES, DBTableID.Quest.Row.QUEST_RUNEMYSTERIES, null, VarPlayerID.RUNEMYSTERIES),
    SCORPIONCATCHER(ObjectID.QUEST_START_ICON_SCORPIONCATCHER, DBTableID.Quest.Row.QUEST_SCORPIONCATCHER, null, VarPlayerID.SCORPCATCHER),
    SCRAMBLED(ObjectID.QUEST_START_ICON_SCRAMBLED, DBTableID.Quest.Row.QUEST_SCRAMBLED, VarbitID.SCRAMBLED, null),
    SEASLUG(ObjectID.QUEST_START_ICON_SEASLUG, DBTableID.Quest.Row.QUEST_SEASLUG, null, VarPlayerID.SEASLUGQUEST),
    SECRETSOFTHENORTH(ObjectID.QUEST_START_ICON_SECRETSOFTHENORTH, DBTableID.Quest.Row.QUEST_SECRETSOFTHENORTH, VarbitID.SOTN, null),
    SHADESOFMORTTON(ObjectID.QUEST_START_ICON_SHADESOFMORTTON, DBTableID.Quest.Row.QUEST_SHADESOFMORTTON, null, VarPlayerID.MORTTONQUEST),
    SHADOWOFTHESTORM(ObjectID.QUEST_START_ICON_SHADOWOFTHESTORM, DBTableID.Quest.Row.QUEST_SHADOWOFTHESTORM, VarbitID.AGRITH_QUEST, null),
    SHADOWSOFCUSTODIA(ObjectID.QUEST_START_ICON_SHADOWSOFCUSTODIA, DBTableID.Quest.Row.QUEST_SHADOWSOFCUSTODIA, VarbitID.SOC, null),
    SHEEPHERDER(ObjectID.QUEST_START_ICON_SHEEPHERDER, DBTableID.Quest.Row.QUEST_SHEEPHERDER, null, VarPlayerID.SHEEPHERDERQUEST),
    SHEEPSHEARER(ObjectID.QUEST_START_ICON_SHEEPSHEARER, DBTableID.Quest.Row.QUEST_SHEEPSHEARER, null, VarPlayerID.SHEEP),
    SHIELDOFARRAV(ObjectID.QUEST_START_ICON_SHIELDOFARRAV, DBTableID.Quest.Row.QUEST_SHIELDOFARRAV, null, VarPlayerID.PHOENIXGANG),
    SHILOVILLAGE(ObjectID.QUEST_START_ICON_SHILOVILLAGE, DBTableID.Quest.Row.QUEST_SHILOVILLAGE, null, VarPlayerID.ZOMBIEQUEEN),
    SINSOFTHEFATHER(ObjectID.QUEST_START_ICON_SINSOFTHEFATHER, DBTableID.Quest.Row.QUEST_SINSOFTHEFATHER, VarbitID.MYQ5, null),
    SLEEPINGGIANTS(ObjectID.QUEST_START_ICON_SLEEPINGGIANTS, DBTableID.Quest.Row.QUEST_SLEEPINGGIANTS, VarbitID.SLEEPING_GIANTS, null),
    SLUGMENACE(ObjectID.QUEST_START_ICON_SLUGMENACE, DBTableID.Quest.Row.QUEST_SLUGMENACE, VarbitID.SLUG2_MAIN, null),
    SONGOFTHEELVES(ObjectID.QUEST_START_ICON_SONGOFTHEELVES, DBTableID.Quest.Row.QUEST_SONGOFTHEELVES, VarbitID.SOTE, null),
    SOULSBANE(ObjectID.QUEST_START_ICON_SOULSBANE, DBTableID.Quest.Row.QUEST_SOULSBANE, VarbitID.SOULBANE_PROG, null),
    SPIRITSOFTHEELID(ObjectID.QUEST_START_ICON_SPIRITSOFTHEELID, DBTableID.Quest.Row.QUEST_SPIRITSOFTHEELID, VarbitID.ELIDQUEST, null),
    SWANSONG(ObjectID.QUEST_START_ICON_SWANSONG, DBTableID.Quest.Row.QUEST_SWANSONG, VarbitID.SWANSONG, null),
    TAIBWOWANNAITRIO(ObjectID.QUEST_START_ICON_TAIBWOWANNAITRIO, DBTableID.Quest.Row.QUEST_TAIBWOWANNAITRIO, null, VarPlayerID.TBWT_MAIN),
    TAILOFTWOCATS(ObjectID.QUEST_START_ICON_TAILOFTWOCATS, DBTableID.Quest.Row.QUEST_TAILOFTWOCATS, VarbitID.TWOCATS_QUEST, null),
    TALEOFTHERIGHTEOUS(ObjectID.QUEST_START_ICON_TALEOFTHERIGHTEOUS, DBTableID.Quest.Row.QUEST_TALEOFTHERIGHTEOUS, VarbitID.SHAYZIENQUEST, null),
    TASTEOFHOPE(ObjectID.QUEST_START_ICON_TASTEOFHOPE, DBTableID.Quest.Row.QUEST_TASTEOFHOPE, VarbitID.MYQ4, null),
    TEARSOFGUTHIX(ObjectID.QUEST_START_ICON_TEARSOFGUTHIX, DBTableID.Quest.Row.QUEST_TEARSOFGUTHIX, VarbitID.TOG_JUNA_BOWL, null),
    TEMPLEOFIKOV(ObjectID.QUEST_START_ICON_TEMPLEOFIKOV, DBTableID.Quest.Row.QUEST_TEMPLEOFIKOV, null, VarPlayerID.IKOV),
    TEMPLEOFTHEEYE(ObjectID.QUEST_START_ICON_TEMPLEOFTHEEYE, DBTableID.Quest.Row.QUEST_TEMPLEOFTHEEYE, VarbitID.TOTE, null),
    THRONEOFMISCELLANIA(ObjectID.QUEST_START_ICON_THRONEOFMISCELLANIA, DBTableID.Quest.Row.QUEST_THRONEOFMISCELLANIA, null, VarPlayerID.MISC_QUEST),
    TOURISTTRAP(ObjectID.QUEST_START_ICON_TOURISTTRAP, DBTableID.Quest.Row.QUEST_TOURISTTRAP, null, VarPlayerID.DESERTRESCUE),
    TOWEROFLIFE(ObjectID.QUEST_START_ICON_TOWEROFLIFE, DBTableID.Quest.Row.QUEST_TOWEROFLIFE, VarbitID.TOL_PROG, null),
    TREEGNOMEVILLAGE(ObjectID.QUEST_START_ICON_TREEGNOMEVILLAGE, DBTableID.Quest.Row.QUEST_TREEGNOMEVILLAGE, null, VarPlayerID.TREEQUEST),
    TRIBALTOTEM(ObjectID.QUEST_START_ICON_TRIBALTOTEM, DBTableID.Quest.Row.QUEST_TRIBALTOTEM, null, VarPlayerID.TOTEMQUEST),
    TROLLROMANCE(ObjectID.QUEST_START_ICON_TROLLROMANCE, DBTableID.Quest.Row.QUEST_TROLLROMANCE, null, VarPlayerID.TROLL_LOVE),
    TROLLSTRONGHOLD(ObjectID.QUEST_START_ICON_TROLLSTRONGHOLD, DBTableID.Quest.Row.QUEST_TROLLSTRONGHOLD, null, VarPlayerID.TROLL_QUEST),
    TWILIGHTSPROMISE(ObjectID.QUEST_START_ICON_TWILIGHTSPROMISE, DBTableID.Quest.Row.QUEST_TWILIGHTSPROMISE, VarbitID.VMQ2, null),
    UNDERGROUNDPASS(ObjectID.QUEST_START_ICON_UNDERGROUNDPASS, DBTableID.Quest.Row.QUEST_UNDERGROUNDPASS, null, VarPlayerID.UPASS),
    VAMPYRESLAYER(ObjectID.QUEST_START_ICON_VAMPYRESLAYER, DBTableID.Quest.Row.QUEST_VAMPYRESLAYER, null, VarPlayerID.VAMPIRE),
    WANTED(ObjectID.QUEST_START_ICON_WANTED, DBTableID.Quest.Row.QUEST_WANTED, VarbitID.WANTED_MAIN, null),
    WATCHTOWER(ObjectID.QUEST_START_ICON_WATCHTOWER, DBTableID.Quest.Row.QUEST_WATCHTOWER, null, VarPlayerID.ITWATCHTOWER),
    WATERFALL(ObjectID.QUEST_START_ICON_WATERFALL, DBTableID.Quest.Row.QUEST_WATERFALL, null, VarPlayerID.WATERFALL_QUEST),
    WHATLIESBELOW(ObjectID.QUEST_START_ICON_WHATLIESBELOW, DBTableID.Quest.Row.QUEST_WHATLIESBELOW, VarbitID.SUROK_QUEST, null),
    WHILEGUTHIXSLEEPS(ObjectID.QUEST_START_ICON_WHILEGUTHIXSLEEPS, DBTableID.Quest.Row.QUEST_WHILEGUTHIXSLEEPS, VarbitID.WGS, null),
    WITCHSHOUSE(ObjectID.QUEST_START_ICON_WITCHSHOUSE, DBTableID.Quest.Row.QUEST_WITCHSHOUSE, null, VarPlayerID.BALLQUEST),
    WITCHSPOTION(ObjectID.QUEST_START_ICON_WITCHSPOTION, DBTableID.Quest.Row.QUEST_WITCHSPOTION, null, VarPlayerID.HETTY),
    XMARKSTHESPOT(ObjectID.QUEST_START_ICON_XMARKSTHESPOT, DBTableID.Quest.Row.QUEST_XMARKSTHESPOT, VarbitID.CLUEQUEST, null),
    ZOGREFLESHEATERS(ObjectID.QUEST_START_ICON_ZOGREFLESHEATERS, DBTableID.Quest.Row.QUEST_ZOGREFLESHEATERS, null, null),

    MINIQUEST_BARCRAWL(-1, DBTableID.Quest.Row.MINIQUEST_BARCRAWL, VarbitID.ZOGRE, VarPlayerID.BARCRAWL);

    private static final Integer SHIELD_OF_ARRAV_146 = VarPlayerID.BLACKARMGANG; // Alternative path for the Shield of Arrav quest
    private static final Integer QUEST_UNDERGROUND_PASS_STATE_162 = VarPlayerID.IBANMULTI;

    private final int questIcon;
    private final int questDBTRow;
    private final Integer questVarbitIfPossible;
    private final Integer questVarPlayer;

    quests(int questIcon, Integer questDBTRow, Integer questVarbitIfPossible, Integer questVarPlayer) {
        this.questIcon = questIcon;
        this.questDBTRow = questDBTRow;
        this.questVarbitIfPossible = questVarbitIfPossible;
        this.questVarPlayer = questVarPlayer;
    }

    public static boolean isQuestComplete(Client client, int questIconObjectID) {
        for (quests q : quests.values()) {
            if (q.questIcon == questIconObjectID) {
                int endState = (int) client.getDBTableField(q.questDBTRow, DBTableID.Quest.COL_ENDSTATE, 0)[0];
                int completionState;
                if (q.questVarbitIfPossible != null) {
                    completionState = client.getVar(q.questVarbitIfPossible);
                }
                else {
                    completionState = client.getVarpValue(q.questVarPlayer);
                }

                if (q.questIcon == ObjectID.QUEST_START_ICON_SHIELDOFARRAV && completionState != endState) {
                    completionState = client.getVarpValue(SHIELD_OF_ARRAV_146);
                }
                else if (q.questIcon == ObjectID.QUEST_START_ICON_UNDERGROUNDPASS && completionState != endState) {
                    completionState = client.getVarpValue(QUEST_UNDERGROUND_PASS_STATE_162);
                }

                return completionState == endState;
            }
        }

        log.error("The Quest icon: " + questIconObjectID + " is not recorded yet. Please raise an issue to correct.");
        return false; // Quest icon wasn't found, therefore show the icon
    }
    public static boolean isQuestComplete(Client client, quests quest) {
        return isQuestComplete(client, quest.questIcon);
    }
}